### ISSUE TITLE
Add any sorting algorithm that have folder in this repo, on any language

### ISSUE THREAD

**Issue by Matrix278** [Matrix278/algorithms#3]
You can create as many PR as you can, but please watch to not have duplicate code

**Comment by saladinreborn** [comment]
I've created PR #11 for linear search algorithm using python language.

**Comment by vishal-wadhwa** [comment]
Hey, have added a go implementation for binary search. Please check: https://github.com/Matrix278/algorithms/pull/12

**Comment by singloon** [comment]
Hi, I've added Java implementation of quick sort. Please check #15

**Comment by afflato** [comment]
Hi @Matrix278 , Adding java version for selection sort in ascending order. Please validate #16

**Comment by Shreyas-Gupta-21** [comment]
Hello I'm Interested to work on this. Pls assign this to me

**Comment by afflato** [comment]
Hi @Matrix278, Adding java version for quick sort in ascending order #22. Please validate. Thanks

**Comment by Matrix278** [comment]
> Hello I'm Interested to work on this. Pls assign this to me

Sure, just create PR, and I will review it

**Comment by verma-shivani** [comment]
hey! I am interested to work on this.
may i add binary search in c++ .

**Comment by Matrix278** [comment]
> hey! I am interested to work on this.
> may i add binary search in c++ .

Sure

**Comment by saladinreborn** [comment]
Hi @Matrix278 , I've added quick sort algorithm using python language. Please check this PR #30

**Comment by AlecsisDuarte** [comment]
Hi @Matrix278,
I just added the bubble sort algorithm for Dart at #32 
Please have a look 👀

**Comment by Matrix278** [comment]
Thank you all for contribution)

**Comment by Matrix278** [comment]
Open again for new hacktoberfest 2021
